# 문자열 심화

## 대소문자 변환

In [2]:
text = "Hello, Python!"

print(text)
print(text.upper())
print(text.lower())

Hello, Python!
HELLO, PYTHON!

## 공백 제거

In [3]:
name = "    Python    "

print(f"원본: '{name}'") # JAVA: name.trim()
print(f"정리 후: '{name.strip()}'")

# 변수와 String 비교
print("공백이 있을 때 비교:", name == "Python")
print("공백 제거 후 비교:", name.strip() == "Python")

원본: '    Python    '

## 문자열 바꾸기

In [5]:
sentence = "파이썬을 배우고 있습니다. 파이썬은 정말 재미있어요."
new_sentence = sentence.replace("파이썬", "Python")

print("원본:", sentence)
print("수정:", new_sentence)

원본: 파이썬을 배우고 있습니다. 파이썬은 정말 재미있어요.
수정: Python을 배우고 있습니다. Python은 정말 재미있어요.

In [6]:
price = "1,500,000원"
clean_price = price.replace(",", "").replace("원", "")
print(int(clean_price))

1500000

## 문자열 나누기

In [8]:
words = "사과,바나나,포도,딸기"
word_list = words.split(",")
print(word_list, len(word_list))

['사과', '바나나', '포도', '딸기'] 4

## 문자열 자르기

In [11]:
phone = "010-1234-5678"

# 앞에서 3글자
print(phone[0:3])
# 가운데 4글자
print(phone[4:8])
# 마지막 4글자
print(phone[-4:])

010
1234
5678

## 문제
이메일 주소에서 아이디와 도메인을 분리하세요.

In [14]:
email = "12345@email.daelim.ac.kr"

parts = email.split("@")
user_id = parts[0]
domain = parts[1]

print("이메일:",email)
print("아이디:",user_id)
print("도메인:",domain)

이메일: 12345@email.daelim.ac.kr
아이디: 12345
도메인: email.daelim.ac.kr

## 문자열 검색

In [16]:
review = "이 제품은 정말 좋아요! 배송도 빠르고 품질도 훌륭합니다."

print("좋아요 포함:", "좋아요" in review)   
print("싫어요 포함:", "싫어요" in review)

if "좋아요" in review or "훌륭" in review:
    print("긍정적인 리뷰입니다.")
if "싫어요" in review or "별로" in review:
    print("부정적인 리뷰입니다.")

좋아요 포함: True
싫어요 포함: False
긍정적인 리뷰입니다.

# 함수 심화

## 함수 기본값

In [19]:
def greet(name, greeting="안녕하세요"):
    print(f"{greeting}, {name}님!")

greet("대림대")
greet("대림대", "반갑습니다")

안녕하세요, 대림대님!
반갑습니다, 대림대님!

In [ ]:
# 할인율 계산
# discount: 0.0~1.0 (0%~100%)
def calculate_price(price, discount=0):
    discounted = price * (1 - discount)
    return discounted

print(f"기본 가격: {calculate_price(10000)}원")
print(f"할인 가격: {calculate_price(10000, 0.1)}원")

기본 가격: 10000원
할인 가격: 9000.0원

## 함수에서 여러값 반환하기

In [27]:
# 최솟값과 최댓값을 동시 반환하는 함수
def min_max(numbers):
    minimum = min(numbers)
    maximum = max(numbers)
    return minimum, maximum

scores = [10,20,30,40,50,60,70,80]
low, high = min_max(scores)
print(f"최솟값: {low}")
print(f"최댓값: {high}")


print(min_max(scores))

최솟값: 10
최댓값: 80
(10, 80)

## 문제
class_scores = [45, 62, 78, 55, 90, 83, 71, 66, 48, 95]
1. 성적 분석 함수 생성
2. 아래와 같은 로그 출력 - 4줄
    - 평균: x.x 점 (소수점 1번째 자리 까지만 출력)
    - 최고점: xx점
    - 최저점: xx점
    - 합격(60점 이상): x명

In [28]:
class_scores = [45, 62, 78, 55, 90, 83, 71, 66, 48, 95]

def analyze_scores(scores):
    average = sum(scores) / len(scores)
    max_score = max(scores)
    min_score = min(scores)
    pass_count = sum(1 for score in scores if score >= 60)
    
    print(f"평균: {average:.1f} 점")
    print(f"최고점: {max_score}점")
    print(f"최저점: {min_score}점")
    print(f"합격(60점 이상): {pass_count}명")

analyze_scores(class_scores)

평균: 69.3 점
최고점: 95점
최저점: 45점
합격(60점 이상): 7명

# Pandas 심화

In [29]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [31]:
# 학생 데이터
grade_data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "korean": [85, 78, 92, 70, 88],
    "math": [90, 82, 95, 75, 91],
    "english": [88, 80, 94, 72, 89]
}

grade_df = pd.DataFrame(grade_data)
grade_df

      name  korean  math  english
0    Alice      85    90       88
1      Bob      78    82       80
2  Charlie      92    95       94
3    David      70    75       72
4      Eva      88    91       89

## 정렬하기

In [34]:
print("----- 국어 점수 낮은 순 -----")
print(grade_df.sort_values("korean"))
print()
print("----- 수학 점수 높은 순 -----")
print(grade_df.sort_values("math", ascending=False))

----- 국어 점수 낮은 순 -----
      name  korean  math  english
3    David      70    75       72
1      Bob      78    82       80
0    Alice      85    90       88
4      Eva      88    91       89
2  Charlie      92    95       94

----- 수학 점수 높은 순 -----
      name  korean  math  english
2  Charlie      92    95       94
4      Eva      88    91       89
0    Alice      85    90       88
1      Bob      78    82       80
3    David      70    75       72

## 새로운 열 추가하기

In [36]:
grade_df["average"] = \
    (grade_df["korean"] + \
        grade_df["math"] + \
            grade_df["english"]) / 3

grade_df["average"] = grade_df["average"].round(1)
grade_df

      name  korean  math  english  average
0    Alice      85    90       88     87.7
1      Bob      78    82       80     80.0
2  Charlie      92    95       94     93.7
3    David      70    75       72     72.3
4      Eva      88    91       89     89.3

In [38]:
grade_df["grade"] = grade_df["average"].apply(lambda x: "A" if x >= 90 else ("B" if x >= 80 else "C"))

grade_df

      name  korean  math  english  average grade
0    Alice      85    90       88     87.7     B
1      Bob      78    82       80     80.0     B
2  Charlie      92    95       94     93.7     A
3    David      70    75       72     72.3     C
4      Eva      88    91       89     89.3     B

## 그룹별 통계

In [39]:
group_average = grade_df.groupby("grade")["average"].mean()
print("등급별 평균:")
print(group_average)

등급별 평균:
grade
A    93.700000
B    85.666667
C    72.300000
Name: average, dtype: float64

In [42]:
# 응용 - 회사 부서별 급여 파악

employee_data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "department": ["HR", "IT", "IT", "HR", "Finance"],
    "salary": [50000, 70000, 75000, 52000, 68000]
}

emp_df = pd.DataFrame(employee_data)

print("----- 부서별 평균 급여 -----")
dept_avg = emp_df.groupby("department")["salary"].mean()
print(dept_avg.round(0))

print("----- 부서별 인원 수 -----")
dept_count = emp_df.groupby("department")["name"].count()
print(dept_count)

----- 부서별 평균 급여 -----
department
Finance    68000.0
HR         51000.0
IT         72500.0
Name: salary, dtype: float64
----- 부서별 인원 수 -----
department
Finance    1
HR         2
IT         2
Name: name, dtype: int64